name: 'Get NAPI Info'
description: 'Extract napi.targets from package.json and generate build matrix'
inputs:
  package-json-path:
    description: 'Path to binding package.json'
    required: false
    default: 'crates/binding/package.json'
  napi-build-command:
    description: 'Command to call napi build. Use this option as an alias to build napi binding package. The directory of the package.json file is the working directory of the command.'
    required: false
    default: 'pnpm build'
outputs:
  matrix:
    description: 'Generated build matrix for napi targets'
    value: ${{ steps.generate.outputs.matrix }}
  binding-directory:
    description: 'Path to directory containing *.node files'
    value: ${{ steps.paths.outputs.binding-directory }}
  targets:
    description: 'List of napi targets'
    value: ${{ steps.generate.outputs.targets }}
runs:
  using: 'composite'
  steps:
    - name: Calculate paths
      id: paths
      run: |
        BINDING_DIR=$(dirname "${{ inputs.package-json-path }}")
        echo "binding-directory=$BINDING_DIR" >> $GITHUB_OUTPUT
        echo "Binding directory: $BINDING_DIR"
      shell: bash
    - name: Generate build matrix
      id: generate
      uses: actions/github-script@v7
      with:
        script: |
          const generateMatrix = require('${{ github.action_path }}/generate-matrix.js');
          await generateMatrix({
            core,
            packageJsonPath: '${{ inputs.package-json-path }}',
            napiBuildCommand: '${{ inputs.napi-build-command }}'
          });
