name: 'Get NAPI Info'
description: 'Extract napi.targets from package.json and generate build matrix'
inputs:
  package-json-path:
    description: 'Path to binding package.json'
    required: false
    default: 'crates/binding/package.json'
  napi-build-command:
    description: 'Command to call napi build. Use this option as an alias to build napi binding package. The directory of the package.json file is the working directory of the command.'
    required: false
    default: 'pnpm build'
outputs:
  matrix:
    description: 'Generated build matrix for napi targets'
    value: ${{ steps.generate.outputs.matrix }}
  binding-directory:
    description: 'Path to directory containing *.node files'
    value: ${{ steps.paths.outputs.binding-directory }}
  targets:
    description: 'List of napi targets'
    value: ${{ steps.generate.outputs.targets }}
runs:
  using: 'composite'
  steps:
    - name: Calculate paths
      id: paths
      run: |
        BINDING_DIR=$(dirname "${{ inputs.package-json-path }}")
        echo "binding-directory=$BINDING_DIR" >> $GITHUB_OUTPUT
        echo "Binding directory: $BINDING_DIR"
      shell: bash
    - name: Generate build matrix
      id: generate
      run: |
        # Check if package.json exists
        if [ ! -f "${{ inputs.package-json-path }}" ]; then
          echo "Error: ${{ inputs.package-json-path }} not found"
          exit 1
        fi

        # Extract napi.targets from package.json
        # Use jq to extract and clean targets in one step
        targets=$(cat "${{ inputs.package-json-path }}" | jq -r '.napi.targets[]?' | sed 's/\r$//')

        if [ -z "$targets" ]; then
          echo "Error: No napi.targets found in package.json"
          exit 1
        fi

        # Debug: Show raw targets
        echo "Raw targets from jq:"
        echo "$targets"
        echo "--- End of raw targets ---"

        # Convert to array for easier processing
        targets_array=()
        while IFS= read -r line; do
          [ -n "$line" ] && targets_array+=("$line")
        done <<< "$targets"

        echo "Found ${#targets_array[@]} targets"

        # Function to get platform configuration
        get_platform_config() {
          local target=$1
          case $target in
            "x86_64-apple-darwin")
              echo '{"host": "macos-latest", "target": "x86_64-apple-darwin", "build": "${{ inputs.napi-build-command }} --target x86_64-apple-darwin"}'
              ;;
            "x86_64-pc-windows-msvc")
              echo '{"host": "windows-latest", "target": "x86_64-pc-windows-msvc", "build": "${{ inputs.napi-build-command }} --target x86_64-pc-windows-msvc"}'
              ;;
            "i686-pc-windows-msvc")
              echo '{"host": "windows-latest", "target": "i686-pc-windows-msvc", "build": "${{ inputs.napi-build-command }} --target i686-pc-windows-msvc"}'
              ;;
            "x86_64-unknown-linux-gnu")
              echo '{"host": "ubuntu-22.04", "target": "x86_64-unknown-linux-gnu", "build": "${{ inputs.napi-build-command }} --target x86_64-unknown-linux-gnu --use-napi-cross"}'
              ;;
            "x86_64-unknown-linux-musl")
              echo '{"host": "ubuntu-22.04", "target": "x86_64-unknown-linux-musl", "build": "${{ inputs.napi-build-command }} --target x86_64-unknown-linux-musl -x"}'
              ;;
            "aarch64-apple-darwin")
              echo '{"host": "macos-latest", "target": "aarch64-apple-darwin", "build": "${{ inputs.napi-build-command }} --target aarch64-apple-darwin"}'
              ;;
            "aarch64-unknown-linux-gnu")
              echo '{"host": "ubuntu-22.04", "target": "aarch64-unknown-linux-gnu", "build": "${{ inputs.napi-build-command }} --target aarch64-unknown-linux-gnu --use-cross"}'
              ;;
            "armv7-unknown-linux-gnueabihf")
              echo '{"host": "ubuntu-22.04", "target": "armv7-unknown-linux-gnueabihf", "build": "${{ inputs.napi-build-command }} --target armv7-unknown-linux-gnueabihf --use-cross"}'
              ;;
            "aarch64-linux-android")
              echo '{"host": "ubuntu-22.04", "target": "aarch64-linux-android", "build": "${{ inputs.napi-build-command }} --target aarch64-linux-android"}'
              ;;
            "armv7-linux-androideabi")
              echo '{"host": "ubuntu-22.04", "target": "armv7-linux-androideabi", "build": "${{ inputs.napi-build-command }} --target armv7-linux-androideabi"}'
              ;;
            "aarch64-unknown-linux-musl")
              echo '{"host": "ubuntu-22.04", "target": "aarch64-unknown-linux-musl", "build": "${{ inputs.napi-build-command }} --target aarch64-unknown-linux-musl -x"}'
              ;;
            "aarch64-pc-windows-msvc")
              echo '{"host": "windows-latest", "target": "aarch64-pc-windows-msvc", "build": "${{ inputs.napi-build-command }} --target aarch64-pc-windows-msvc"}'
              ;;
            *)
              echo ""
              ;;
          esac
        }

        # Validate targets and build matrix
        matrix_items=()
        unsupported_targets=()

        for target in "${targets_array[@]}"; do
          # Debug: print the target being processed
          echo "Processing target: '$target'"
          echo "Target length: ${#target}"
          
          # Clean the target string more aggressively
          target=$(echo "$target" | tr -d '\r\n\t ' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
          echo "Cleaned target: '$target'"
          echo "Cleaned target length: ${#target}"
          
          config=$(get_platform_config "$target")
          echo "Config for '$target': '$config'"
          if [ -n "$config" ]; then
            matrix_items+=("$config")
          else
            echo "ERROR: No config found for target '$target'"
            unsupported_targets+=("$target")
          fi
        done

        # Check for unsupported targets
        if [ ${#unsupported_targets[@]} -gt 0 ]; then
          echo "Error: Unsupported targets found: ${unsupported_targets[*]}"
          exit 1
        fi

        # Generate matrix JSON
        matrix_json=$(printf '%s\n' "${matrix_items[@]}" | jq -s -c '{"settings": .}')

        # Use proper multiline output format for GitHub Actions
        {
          echo "matrix<<EOF"
          echo "$matrix_json"
          echo "EOF"
        } >> $GITHUB_OUTPUT

        # Also output targets for reference
        targets_json=$(echo "$targets" | jq -R -s -c 'split("\n")[:-1]')
        {
          echo "targets<<EOF"
          echo "$targets_json"
          echo "EOF"
        } >> $GITHUB_OUTPUT

        echo "Generated matrix for targets: $targets"
        echo "Matrix: $matrix_json"
      shell: bash
